arr_locations = [
  {
    "N": 53,
    "location": "11.4782434,104.9677257",
    "Z1_price": "",
    "Type": "Shophouse",
    "Lot_Type": "End Lot",
    "Land_Width": 5.5,
    "Land_Length": 21.3,
    "No_of_Floors": 3,
    "Bldg_Width": 21.3,
    "Bldg_Length": 4.5,
    "Title_Deed": "Hard",
    "Kitchen": 1,
    "Living_Room": 1,
    "Road_Size": 12,
    "Bedroom": 6,
    "Bathroom": 7,
  },
  {
    "N": 54,
    "location": "11.4811079,104.9705898",
    "Z1_price": "",
    "Type": "Single-Detached",
    "Lot_Type": "Corner Lot",
    "Land_Width": 20,
    "Land_Length": 27,
    "No_of_Floors": 3,
    "Bldg_Width": 12,
    "Bldg_Length": 16,
    "Title_Deed": "Hard",
    "Kitchen": 1,
    "Living_Room": 2,
    "Road_Size": 8,
    "Bedroom": 5,
    "Bathroom": 6,
  },
  {
    "N": 55,
    "location": "11.4688162,105.0045277",
    "Z1_price": "",
    "Type": "vacant_Land",
    "Lot_Type": "Other",
    "Land_Width": 40,
    "Land_Length": 58,
    "No_of_Floors": "",
    "Bldg_Width": "",
    "Bldg_Length": "",
    "Title_Deed": "",
    "Kitchen": "",
    "Living_Room": "",
    "Road_Size": "",
    "Bedroom": "",
    "Bathroom": "",
  },
  {
    "N": 56,
    "location": "11.4982740,104.9927523",
    "Z1_price": "",
    "Type": "Shophouse",
    "Lot_Type": "End Lot",
    "Land_Width": 6.5,
    "Land_Length": 23.6,
    "No_of_Floors": 2,
    "Bldg_Width": 4.5,
    "Bldg_Length": 16,
    "Title_Deed": "Hard",
    "Kitchen": 1,
    "Living_Room": 1,
    "Road_Size": 30,
    "Bedroom": 4,
    "Bathroom": 5,
  },
  {
    "N": 57,
    "location": "11.5122971,104.9935984",
    "Z1_price": "",
    "Type": "Vacant_Land",
    "Lot_Type": "Other",
    "Land_Width": 34,
    "Land_Length": 114,
    "No_of_Floors": "",
    "Bldg_Width": "",
    "Bldg_Length": "",
    "Title_Deed": "",
    "Kitchen": "",
    "Living_Room": "",
    "Road_Size": "",
    "Bedroom": "",
    "Bathroom": "",
  },
  {
    "N": 58,
    "location": "11.5279275,104.9877107",
    "Z1_price": "",
    "Type": "Shophouse",
    "Lot_Type": "End Lot",
    "Land_Width": 11.57,
    "Land_Length": 24.6,
    "No_of_Floors": 2.5,
    "Bldg_Width": 4.5,
    "Bldg_Length": 18,
    "Title_Deed": "",
    "Kitchen": 0,
    "Living_Room": 0,
    "Road_Size": 7.5,
    "Bedroom": 4,
    "Bathroom": 5,
  },
  {
    "N": 59,
    "location": "11.5345839,104.9926688",
    "Z1_price": "",
    "Type": "Linkhouse",
    "Lot_Type": "End Lot",
    "Land_Width": 5.55,
    "Land_Length": 21,
    "No_of_Floors": 2.5,
    "Bldg_Width": 4.3,
    "Bldg_Length": 14.5,
    "Title_Deed": "Hard",
    "Kitchen": 1,
    "Living_Room": 1,
    "Road_Size": 8,
    "Bedroom": 4,
    "Bathroom": 5,
  },
  {
    "N": 60,
    "location": "11.4444102,104.8910239",
    "Z1_price": "",
    "Type": "Vacant_Land",
    "Lot_Type": "Other",
    "Land_Width": 100,
    "Land_Length": 200,
    "No_of_Floors": "",
    "Bldg_Width": "",
    "Bldg_Length": "",
    "Title_Deed": "",
    "Kitchen": "",
    "Living_Room": "",
    "Road_Size": "",
    "Bedroom": "",
    "Bathroom": "",
  },
    {
    "N": 61,
    "location": "11.4691558,105.0133110",
    "Z1_price": "",
    "Type": "Vacant_Land",
    "Lot_Type": "Other",
    "Land_Width": 15,
    "Land_Length": 107,
    "No_of_Floors": "",
    "Bldg_Width": "",
    "Bldg_Length": "",
    "Title_Deed": "",
    "Kitchen": "",
    "Living_Room": "",
    "Road_Size": "",
    "Bedroom": "",
    "Bathroom": "",
  },
]